### ISSUE TITLE
Get cargo ndk run again

### ISSUE THREAD

**Issue by ineiti** [c4dt/lightarti-rest#103]
Problem: the `build-android` job on the `lint-build-test` github workflow fails with an obscure error about not being able to link with `gcc`.

The best link I found is this: https://github.com/rust-lang/rust/pull/85806 - but I still cannot get it to work again. I even tried to recompile `lightarti-rest/main`, and this fails, too!

Interestingly enough, `lightarti-rest-androi` succeeds: https://github.com/c4dt/lightarti-rest-android/runs/7342786722

So please use a day or two to find out if you can get `cargo ndk` to work again in that workflow. If it doesn't work after this time, we'll have to find another way.

The goal is to be able to build this: https://github.com/c4dt/lightarti-rest/pull/101

**Comment by tharvik** [comment]
Hum, that's weird indeed. Found a workaround at #104.

I also rebased #101 on #104 and it's green now :)
