### ISSUE TITLE
Measure node churn

### ISSUE THREAD

**Issue by ineiti** [c4dt/lightarti-rest#40]
Need to make sure that there is not a too high churn in the nodes over time. This is to avoid that the files get outdated too fast.

**Comment by ineiti** [comment]
The tests and calculations have been done by @laurent-girod , but I would like to have a pointe here showing the results. And eventually a repo where the tests are done?

**Comment by laurent-girod** [comment]
So, I have an analysis in a Jupyter notebook, but I still need to complete it with a better documentation.

When @wouterl will give me it's OK, I am going to release the repo in public.

**Comment by ineiti** [comment]
@laurent-girod @wouterl I'm cleaning up old issues - is this still possible to have? Or should I just close the issue with `not happening`?

**Comment by ineiti** [comment]
OK, timeout... Closing this issue.
