### ISSUE TITLE
Make sure different routes are tried

### ISSUE THREAD

**Issue by ineiti** [c4dt/lightarti-rest#80]
While investigating the failure in https://github.com/c4dt/lightarti-rest/runs/3963994558?check_suite_focus=true#step:9:85, @laurent-girod wrote:

```
This is the incriminated relay, apparently, its maintainer changed its ORPort from 443 to 993.
[...]
So, if you wait for the next consensus, the problem might solve itself.
(or by rerunning immediately, as Arti randomly selects the routers to build a circuit.)
```

What is strange is that I thought it'll try three circuits anyway. The test is here:
https://github.com/c4dt/lightarti-rest/blob/ca06e663fdae03b17f53bb4852275f45577eb994/src/lightarti.rs#L95
and the retry is here:
https://github.com/c4dt/lightarti-rest/blob/ca06e663fdae03b17f53bb4852275f45577eb994/src/lightarti.rs#L53
so why doesn't it choose a new circuit?

**Comment by cgrigis** [comment]
Per my understanding, the issue was that depending on where the error occurred, it would result in an immediate return due to `context()`, as in the trace from the CI (where the error happened during the `tor.connect()` call).
