### ISSUE TITLE
unable to connect to c4dt.org

### ISSUE THREAD

**Issue by tharvik** [c4dt/lightarti-rest#92]
When trying to get https://www.c4dt.org, it fails with
```
send request: tor connect

Caused by:
    0: tor: operation timed out at exit: exit timed out
    1: exit timed out
```

**Comment by ineiti** [comment]
Same for admin.ch, perdu.com

**Comment by cgrigis** [comment]
So with #93, `admin.ch` and others seem to work. `c4dt.org` and `perdu.com` still timeout, but in my experience they also do that under regular Arti.

**Comment by ineiti** [comment]
Just for the record: I tried c4dt.org and epfl.ch with the tor browser, and both are very flaky. But usually after a couple of changes in the circuit, they do connect.

I sent a request to support-icit and ask them whether there is something we con do to improve this, as other sites seem to work without issues.
